# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

- name: App Service Web App Build Action
  uses: Azure/appservice-build@v2
  with:
    # Relative path (within the repository) to the source directory of the project you want to build; if no value is provided for this, the root of the repository ("GITHUB_WORKSPACE" environment variable) will be built.
    source-directory: # optional
    # Programming platform used to build the web app; if no value is provided, Oryx will determine the platform to build with. The supported values are "dotnet", "nodejs", "php" and "python".
    platform: # optional
    # Version of the programming platform used to build the web app; if no value is provided, Oryx will determine the version needed to build the repository.
    platform-version: # optional
    # The directory where the build output has to be put.
    output-directory: # optional
    
name: Build and deploy ASP.Net Core app to Azure Web App - bvitest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'

    - name: Build with dotnet
      run: dotnet build

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bvitest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25eecf740a4d4028aceaaf6ee20cce87 }}
        package: .
